apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: airflow
data:
  GITSYNC_USERNAME: dGllbnBxdA==
  GITSYNC_PASSWORD: Z2hwX08xZWhNd0pxT0RvbmdVaHlmN3pxb0plMHd1bjREMzN5V2FwbA==
  GIT_SYNC_USERNAME: dGllbnBxdA==
  GIT_SYNC_PASSWORD: Z2hwX08xZWhNd0pxT0RvbmdVaHlmN3pxb0plMHd1bjREMzN5V2FwbA==